### PR TITLE
Defensive use of HTTP connections

### PR DESCRIPTION
**Pull request by clechasseur**
These changes were inspired by similar changes merged
in the Stash plugin. They use short timeout values and
cancellable HTTP tasks to ensure that the plugin does
not run out of sockets, which can completely jam Jenkins.

### CODE REVIEW

**Comment by clechasseur** [comment]
I fixed the compilation errors, but it seems some of the tests fail for a weird reason that seems unrelated to this plugin. I ran the tests here locally before pushing and they were working okay...

**Comment by clechasseur** [comment]
I noticed that the failing tests are the same as those that were failing in the previous pull request. Is it possible that there's an issue with the tests?

**Review by damovsky — CHANGES_REQUESTED** [review]
hi @clechasseur ,
 can you please resolve those conflicts? 
thanks
Martin

**Comment by clechasseur** [comment]
Looks like I no longer have the repo I used to create the PR. I'll close this and create a new fork to fix things, then resubmit.

**Pull request closed without merging**
