### PR TITLE
Pre-release Merge

### PR DESCRIPTION
**Pull request by CodeMonk**
- Added rudimentary support for jenkins-server
- Added improvement for build short description from PR
- Fixed bug in use of RevisionParameterAction. While I'm still not convinced that this is the best way to pick a particular commit, this fix seems to have removed all side effects.
- Added a thread pool queue and some changes to the way we were reading http responses to avoid the cron thread from dying (was getting hung on socket timeouts inside if req.getResponseBodyAsStream(), so we moved to req.getResponseBodyAsString
- Fixed bugs caused with jenkins server support (was breaking trigger phrase in comment, among other things)
- Re-versioned for a 1.4.29 release instead of a 1.5.0 since this is yet another maintenance release.

### CODE REVIEW

**Comment by CodeMonk** [comment]
For grins, I have requested all contributors in the above commits to review this PR, but, that should not hold up the release. I have been running this code (minus merges) live for several days, and am loading  it up love at my company now, for a final sanity check to catch any merge errors.

Ciao!

**Comment by Dohbedoh** [comment]
Any chance we could add a `Jenkinsfile`  - with the content `buildPlugin()` - to have https://ci.jenkins.io automatically build the `.hpi`s ?

**Comment by CodeMonk** [comment]
> Any chance we could add a `Jenkinsfile` - with the content `buildPlugin()` - to have https://ci.jenkins.io automatically build the `.hpi`s ?

Sure! Do you have an example of another repo with a Jenkinsfile as an example?

**Review by chrisLeeTW — APPROVED** [review]

**Comment by Dohbedoh** [comment]
Yes. For example: https://github.com/jenkinsci/support-core-plugin/blob/master/Jenkinsfile. It is a simple function.
More details here: https://github.com/jenkins-infra/pipeline-library

**Comment by CodeMonk** [comment]
@Dohbedoh Lol - I didn't realize you were being literal with buildPlugin()

Done.

**Review by Dohbedoh — APPROVED** [review]

**Pull request merged**
