### PR TITLE
Development webhook support

### PR DESCRIPTION
**Pull request by Joehunk**
Reworked the plugin to trigger based on Bitbucket Webhooks rather than a cron job.  Also supports rebuilding when a pull request is updated.

Should address:
- [JENKINS-30277](https://issues.jenkins-ci.org/browse/JENKINS-30277)
- [JENKINS-26786](https://issues.jenkins-ci.org/browse/JENKINS-26786)
- [JENKINS-26785](https://issues.jenkins-ci.org/browse/JENKINS-26785)

Might address (not tested):
- [JENKINS-29919](https://issues.jenkins-ci.org/browse/JENKINS-29919)

### CODE REVIEW

**Comment by rubao** [comment]
awesome! probably it will fix a problem that I have with cron.

any news about when this feature will be merged?

**Comment by Joehunk** [comment]
I actually have not heard anything.  Apparently I am supposed to go through
official Jenkins channels in the event I don't hear from the maintainer in
a couple weeks.  It's nearing that time, so I'll contact them soon.

**Comment by bsideup** [comment]
:-1: Please, _do not_ accept this PR. Cron based functionality shouldn't be dropped just as is. There are a lot of Jenkins private deployments, unavailable from external network, it will break them all. 

This change could be done as addition, not regression.

**Comment by Joehunk** [comment]
Given some time, I could redo this change as allowing a choice between cron
job or webhook.  For the record however, I don't think the cron job support
is very solid and has a couple serious issues such as the tendency to get
stuck in an infinite build loop.  I liked the amount of code cleanup I was
able to do with a complete replacement.

Also, I confess I don't understand the use case for a Jenkins deployment
that us unavailable to an external network.  Even the cron job must be able
to contact Bitbucket to work, so it must also be able to access the
Internet.  For the case of an on-premise deployment of Bitbucket, then both
Bitbucket and Jenkins will be on the private network.  Can you please
explain a case where the cron job could have the ability to contact the
Bitbucket server, but the webhook would not be accessible?  Do you have
such a case?

Meantime, we have been using the build from my fork internally and it has
been working great, so if anyone wants webhook support before this is
resolved, feel free to use my fork.

**Comment by bsideup** [comment]
@Joehunk yes, we have this case. Our Jenkins deployed in our internal network, it can contact public network, but public network can't reach it (i.e. classic NAT case)

**Comment by bwilczek** [comment]
@Joehunk : is there any progress on this case? We are also interested in this feature in our organization.

**Comment by Joehunk** [comment]
Well, my fork of the repo with the plugin is still live and you are welcome
to use it.  I have not yet blocked out the time to do the necessary work to
get it pulled into the main line, but it's completely usable in its current
form from my fork.  We have been using it that way for over a year with no
issues.

**Comment by damovsky** [comment]
Hi folks.
what we will do with this PR?

besides of conflicts in branch....there is an recommendation from @bsideup to decline this PR.  

What do you think?

**Comment by Joehunk** [comment]
It's been open for a long time (more than a year).  We are using it
internally and it's worked great so it's been tough to get the
time/motivation to work on it to the point where it can be integrated.
It's fine with me if you decline it, I can't promise that I'll ever get
around to getting it in shape to be accepted.  If I do, I'll open a second
PR.

-Charles

**Comment by damovsky** [comment]
sorry guys...I'm not fan of declining PR, but here I have to say no. The reason is that this PR will break the existing functionality - triggering the plugin by cron, as @bsideup mentioned. 

I'm open to adding these feature as an extension to existing cron triggers...

**Pull request closed without merging**
